### PR TITLE
add xxhash3_128 and xxhash3_64 algorithms

### PR DESCRIPTION
**Pull request by jwaggs**
- added the new xxhash algorithms.
- bumped xxhash library to 2.0

### CODE REVIEW

**Comment by jwaggs** [comment]
This will close issue #27

**Comment by ptrpfn** [comment]
The XML files don't validate against the XSD yet with the new hash formats.

```
% ./ascmhl.py create -h xxh3_64 A002R2EC 
 % ./ascmhl.py xsd-schema-check A002R2EC/ascmhl/0001_A002R2EC_2021-01-27_092931.mhl
ERROR: A002R2EC/ascmhl/0001_A002R2EC_2021-01-27_092931.mhl didn't validate against XSD!
Issues:
A002R2EC/ascmhl/0001_A002R2EC_2021-01-27_092931.mhl:8:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{urn:ASC:MHL:v2.0}xxh3_64': This element is not expected. Expected is ( {urn:ASC:MHL:v2.0}metadata ).
```

I will add the question about the new XML elements (e.g. `<xxh3_64>` and `<xxh3_128>`, or just `<xx3>` for the 128 bit variant) to the group meeting for a quick confirmation that we can proceed with that extension of the XSD.

**Comment by jwaggs** [comment]
We decided in the meeting today to change the default hash algorithm to the new xxh3_128 variant. This will grant both speed and collision space improvements.

We also decided to keep the xxh3_64 and xxh3_128 tag naming convention (which was insipired by the xxhash library implementation itself).

I'll flip the default in an upcoming commit before we merge this PR.

**Comment by jwaggs** [comment]
Need to convert 14 tests to either:

- explicitly invoke the `xxh64` algorithm
or
- change the referenced checksum values in the tests to the new default `xxh3_128`

**Comment by jwaggs** [comment]
@ptrpfn this should be ready for merge now. all tests pass.

**Review by ptrpfn — APPROVED** [review]
All test are working again, looks good.

**Pull request merged**
