### PR TITLE
Adding the hashdate attribute to file hash entries (in XML)

### PR DESCRIPTION
**Pull request by ptrpfn**
In last meeting we found that the ascmhl tool doesn't write the `hash_date` attribute in hash entries. 

This pull requests adds this attribute by 

* filling the `hash_date` attribute with the current date and time (preserving milliseconds), and
* skipping directory hashes, as they might not be considered as "hashed" at any specific moment. 

If we also want to add the `hash_date` attribute to directory hashes, this can easily be enabled in `hashlist_xml_parser.py`, method `_media_hash_xml_element`, line 221.

### CODE REVIEW

**Comment by jwaggs** [comment]
Looks good except I could certainly see the dir hash time stamps being useful. 

For example if a new file is added the dir hash value would be updated - so it would help to know when it was last computed potentially.

**Review by jwaggs — DISMISSED** [review]
i think a case could be made to add in the dir hash time stamps but ill go ahead and approve this as is for now.

**Comment by ptrpfn** [comment]
Proposal: 
* Enable hashdate also for directory hashes
* State in the specification that in case of directory hashes the "hashdate" means date and time of computation

**Comment by jwaggs** [comment]
> Proposal:
> 
> * Enable hashdate also for directory hashes
> * State in the specification that in case of directory hashes the "hashdate" means date and time of computation

agreed.

**Comment by jwaggs** [comment]
@ptrpfn let me know if you expected any other changes to the code other than the one line commit I just pushed to this branch.

Once you've had a chance to ok that change I can get this merged in.

**Review by jwaggs — APPROVED** [review]

**Pull request merged**
