### PR TITLE
Make ascmhl and mhllib pip installable

### LINKED ISSUE #45: PIP installer
Create an installer package for easy install

### PR DESCRIPTION
**Pull request by cbenhagen**
The cli interface is installed to the users `$PATH` using [`entry_points`](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html). I took the liberty to remove the .py ending from the tools name as it looks cleaner to use.

So far this PR only enables installing from a git repo with:
`pip3 install git+https://github.com/ascmitc/mhl.git`

or locally with:
`pip3 install .`

I am happy to help publish this package to [PyPI](https://pypi.org/) and would propose to setup GitHub actions to automatically publish a git tag when it passes all unit tests. I already used git tags as version in the `setup.py` and cli interface to make this easier.

`ascmhl_tool_version` and `ascmhl_tool_name` in `__version__.py` are still hardcoded. Using `pkg_resources.get_distribution("mhl").version` or the `write_to` option of `setuptools_scm ` currently breaks the unit tests as the .mhl files contain those values. But if you generally like this approach, I am sure we can find a solution to this.

Fixes #45

### CODE REVIEW

**Comment by jwaggs** [comment]
@cbenhagen thanks for opening this PR.

I'd like to come up with a way to keep `setup.py` and the contents of `requirements.txt` in sync with each other. An option is to read the requirements into setup.py to deduplicate it...

I've found an example of what I'm talking about in the [sentry repo](https://github.com/getsentry/sentry/blob/master/setup.py#L82)

If we split the requirements file into two files (a file for the base install dependencies, then another file for the testing dependencies)... then the `install_requires` section of setup.py would simply load the base requirements and the `tests_require` section would parse the test requirements file.

The one caveat here is requirements files are usually pinned to exact versions, while setup.py files often specify version ranges to allow for end users to upgrade. For that reason I'm torn on the approach I want to take here.

> would propose to setup GitHub actions to automatically publish a git tag when it passes all unit tests.

We do already have a github action which builds and tests - it could be modified to add the necessary tag. Also, per this PR it would seem the [github-action](https://github.com/ascmitc/mhl/blob/9da9125ff7d7ffe50a720ad6c3841a6c55267b76/.github/workflows/build%2Btest.yml#L26-L27) should be updated to use your new `setup.py` file rather than the requirements file.

**Comment by jwaggs** [comment]
Also - I agree the version should not be hardcoded - feel free add your proposed solution to this PR. We can update the test as needed to accommodate.

**Comment by cbenhagen** [comment]
Thank you for the quick response!

I also wish there was a good way to unify the dependencies in `setup.py` and `requirements.txt` but as they have different purposes it might just not be doable. One often recommended way would be to use a `requirements.txt` containing a single dot character. While this allows installing with `pip3 install -r requirements.txt` this would basically be the same as completely removing the `requirements.txt` recommending to use `pip3 install .`.

I think, in the `setup.py` we should not force strict versions on users, but only specify the minimal versions required.  For packages known to use semantic versioning, `package_name ~= X.Y` could be used instead of a range, to make sure only compatible major versions will be used.

For development and deployment I am using [Pipenv](https://pipenv.pypa.io) in many projects to pin versions of all dependecies and sub-dependencies and am very happy with it so far. Did you consider using it? I know there are mixed feelings about this package in the Python community. Would love to hear your thoughts.

For CI I usually use the pinned versions from Pipenv hence why I currently left the GitHub action untouched, but it might also be nice to periodically run the tests with the latest updates of the dependencies installed with `pip3 install -U .` to catch issues with updated dependencies.

I do not yet have a good solution to fix the version and package name in the golden / integration tests. Maybe we just search and replace a placeholder in the .mhl files before running the tests?

**Comment by jwaggs** [comment]
@cbenhagen this is great feedback. 

Pipenv was not something I had used before today, but I played with it a bit this morning. It addresses several of the things we are discussing, so it seems a good fit. The lock file approach is much more in line with how dependencies are usually recorded in other popular languages - so I like it. I'm ok with giving Pipenv a try in this project.

Would you like to add the `Pipenv` and `Pipenv.lock` file to this PR? 

> I do not yet have a good solution to fix the version and package name in the golden / integration tests.

Off the top of my head I'm not sure which tests would break other than the "scenario" tests - which are their own little bastardized thing. Those can usually be resolved by running the `examples/scenarios/_create_README.sh` script. Are there others tests that fail?

**Comment by jwaggs** [comment]
@cbenhagen for the sake of moving things along, I'm going to go ahead and merge this PR since I haven't heard back.  

If you decide to contribute again I'd welcome another PR with some of the above discussed changes.

**Review by jwaggs — APPROVED** [review]

**Comment by cbenhagen** [comment]
Thank you for merging and sorry for the delay. I am looking forward to contribute more!

**Pull request merged**
