### PR TITLE
Hasher Refactor

### PR DESCRIPTION
**Pull request by jwaggs**
Refactored the hasher to clean things up quite a bit.
Removed a lot of redundant code.
Abstracted common code between the "HexHashers" and the C4Hasher.
Added hash tests.

### CODE REVIEW

**Comment by jwaggs** [comment]
I'm marking this as a draft until I clean up a few of the final tests and TODOs

**Comment by jwaggs** [comment]
Worth mentioning almost all changes worth reviewing are contained within the hasher.py module itself. The changes in other files are primarily just propagating some function name changes to where they were used, as well as regenerating the scenarios.

**Comment by jwaggs** [comment]
ready for review @ptrpfn

**Review by ptrpfn — COMMENTED** [review]
Did a code review, all changes look good. 
* `hasher.py` got a major cleanup/rewrite with new behavior as discussed [here in Slack].(https://ascmitcwfmm.slack.com/archives/CD271NEER/p1637356394041400?thread_ts=1636759995.004900&cid=CD271NEER)
* scenario tests are recreated to match new directory hashes
* also in this PR: typo fix in XSD (and necessary code and example changes)

Would propose to wait final approval until discussion about possible renaming of directory hashes due to new behavior.

**Comment by jwaggs** [comment]
@ptrpfn I'm fine with waiting til after meeting to merge.

BUT - I think this should be merged before a name change just to keep the PRs as contained as possible.

There was a lot of naming refactor already in this PR so I'd like to separate additional changes out even if they are quick.

**Review by ptrpfn — APPROVED** [review]
As discussed in the group meeting today there are no more changes planned or open. Merging the PR into master branch can proceed.

**Pull request merged**
