### PR TITLE
Use Black

### LINKED ISSUE #75: Use Black formatter for consistent code formatting
I'd like to propose the use of the [Black code formatter](https://github.com/psf/black). This helps a lot to have a consistent formatting style. It is used by many popular Python projects for the sake of not having to discuss formatting ever again.

While it is opinionated and does not provide many config options by design, one thing we would need to decide on is the line length. An old and endlessly discussed topic. Python once specified a length of 72 characters in their PEP 8 style guide. The currently enforced max line length by the linter in the CI pipeline is set to 127 characters. PyCharm uses 120 characters by default so this is what I would often use in projects but I would be fine with either number. What are your opinions on this?

Once decided on using Black, the style can be enforced using a GitHub Action. I already prepared a PR for that.

### PR DESCRIPTION
**Pull request by cbenhagen**
This PR enables Black code formatting and includes a first reformat. Commits are not squashed yet to show the effects of the string normalization option. 

Fixes #75

### CODE REVIEW

**Comment by jwaggs** [comment]
@cbenhagen there was a conflict introduced once i merged the other PyPi PR #73 - i resolved it but would like for you to go ahead and confirm that my resolution was in the order you expected.

Also - the formatter doesn't like the test_scenarios file. If you could push the formatted code one more time that'd be appreciated. Thanks.

**Comment by cbenhagen** [comment]
@jwaggs I reformatted the scenarios file. I am not sure what your resolution was. Do you remember in which file the conflict was?

**Comment by jwaggs** [comment]
@cbenhagen i already merged it into this PR - see commit [7c5e886419899de998fcfc5bada18e54e02abdcc](https://github.com/ascmitc/mhl/pull/76/commits/7c5e886419899de998fcfc5bada18e54e02abdcc)

**Comment by cbenhagen** [comment]
LGTM

**Review by jwaggs — APPROVED** [review]

**Pull request merged**
