### PR TITLE
Feature mhllib

### PR DESCRIPTION
**Pull request by ptrpfn**
Writing a library that encapsulates access to a given (nested) asc-mhl stucture.

The library has 
* model classes for hashlist, chain, and entire history
* backends for all model classes for reading and writing (e.g. XML files, asc-mhl folders, ..)
* a creation session for new generations to be used by client applications
* tests for a bunch of things (especially the complicated stuff as the nested scenarios)

Replaced the old command line tool by a new one that uses the library.

TODOs new features in library:
* add feature for ignore pattern (currently not documented in MHL files)
* add creation of directory hashes

TODOs remaining tasks in library:
* add missing verification of chain.txt
* better and more error handling
* improve / generate documentation

TODOs in CLI (outside the library):
* separate "verify" (just check) and "seal" (create a new generation for an entire folder) commands
* separate debug commands (verify-paths) e.g. from real-world scenario commands (verify, seal, also see above)

TODOs in project
* update readme file

### CODE REVIEW

**Comment by jwaggs** [comment]
@ptrpfn and @asmpfn lets discuss project structure. 

When I build out initial structure for any project I often consider the import paths that will result. With the way this has been refactored, someone who decides to utilize this tool will end up importing something like this: 

`from mhl.src.mhllib.mhl_history_fs_backend import MHLHistoryFSBackend`

There are a lot of redundant descriptors in there. Something like this would be more preferable:

`from mhl.history import MHLHistoryManager`

This can be accomplished by flattening our package structure and simplifying our naming schemes... "mhl" is not necessary as a folder or file name anywhere in the structure since it will be the root of the import path externally, and internally we just use relative imports since everything would be flattened into a single package. 

Here is a good article I use as a refresher sometimes on project structure: 
[Structuring Your Project](https://docs.python-guide.org/writing/structure/) article.

Here are some good repositories that I referenced when considering these recommendations:
[requests](https://github.com/psf/requests)
[flask](https://github.com/pallets/flask)
[compose](https://github.com/docker/compose)
[sanic](https://github.com/huge-success/sanic)

1. We should be able to run pytest from the root directory.
2. There is a second requirements.txt and an extra readme that were added to the src/ folder. These should be removed in favor of files at root of repository.
3. We need to add the repository license to the root of the structure.
4. The Documentation folder should be renamed docs/ in accordance with the python guidelines. Static site generation routines and output will reside in this directory in a future PR.
5. The Scenarios folder should likely move into an examples/ folder as is common for such things. See above repositories for my motivation behind this.

I'll open a Pull Request in a few minutes to address each of the issues in this comment.

**Comment by jwaggs** [comment]
Guys I'm going to pause my review until I get some feedback on the existing points I've made so far and before I flood this thread with more notes. Much of the functionality from the master branch has been stripped or has yet to be re-implemented in this pull request. I'm wondering if this PR was opened prematurely. I've already mentioned the directory checksums went missing in my prior comment, but I also see that a lot of the CLI command options have been removed and the context work for the CLI has been stripped entirely as well. I can't distinguish if you intended to strip these things, or simply never got around to adding them back in. While there is forward progress on the models there is regression as well. I do not consider it acceptable to simply scrap everything and rewrite the library without taking into consideration all of the existing functionality. When I refactor your code, I don't just delete chunks of functionality. Directory checksums have been a forefront concern for quite some time now and they were skipped entirely in this rewrite. I have notes on how best to achieve each of these things moving forward given the state of the branch, but since directory checksums were not considered during your rewrite, it would also require me to refactor your refactored code even more than I already have. Therefor, I am going to await your input before continuing to hack at this.

**Comment by asmpfn** [comment]
@jwaggs thanks a lot for your great feedback so far.

I'm just back from a 4 week parental leave and will work my way through it in detail the next days.
But from a first look it seems to be exactly the kind of feedback on project structure and python best practices I was hoping to get, since I'm personally not so familiar with python. So thanks a lot!

I'm sorry that due to my leave there might be some misunderstandings about the current state of the implementation and what happened to existing features.
Since it was more like a rewrite than a refactoring I was together with Patrick until now focusing on getting the initial structure right and setting up a working test environment etc. incorporating your feedback I'd say is part of that.
We will of course continue to re-implement all existing features from the initial implementation based on the new structure and any help you can give is highly appreciated. I agree that it doesn't make sense to merge it into the master branch until we got to this point.

Looking forward to continue working on this together the coming weeks.

**Comment by jwaggs** [comment]
@asmpfn congrats on the new kiddo if that's what parental leave was for!?

As for technical matters, I'm glad you found the feedback useful. Whenever you have time to wrap back around to this PR let me know and we can jump on a call to hash out the best way to finish things up for v1... shouldn't be too difficult to reintegrate the missing chunks and finalize structure. Cheers.

**Comment by asmpfn** [comment]
@jwaggs sorry for the delayed reply the current Covid-19 situation took a lot of my time. But we are all safe and I hope it's the same for you.
I finally found some time to work through your feedback. And as I expected it's very valuable so thanks again for that. I'm happy to further discuss some of your points, see my remarks below.

I agree that we are probably not too far away from finishing a v1 based on the new architecture. But with my other duties in mind I don't think I'll have much time the next two weeks. Would the last week of April work for you to kick this off? I hope that my todo list has become a bit shorter until that point.

### Here my feedback notes:

I like the new structure of the repository and I agree that is more simple and similar to how other python frameworks are organized.

### About the backend classes:
The idea here was to separate the conceptual model from the actual representation on disk.
The idea is to be prepared for different format implementations that might come up in the future.
For example I understood that there was a discussion about having a JSON based mhl representation instead of xml.
Having both could be relatively simple if we for example have a XML and a JSON backend class that implement all the serialization and parsing code separately. But the exact same model classes could be use since they are not tied to a specific format themselves.
I agree that the class itself is probably useless and from what I understand we could also use module level functions. But I would like to keep it in a separate file to keep the initial separation.
I learned that it helps a lot to keep things that are conceptional different also technically separated to enforce the separation and if it only helps my own programming discipline ;)
But to keep things simple for the library we can hide the existence of the backends by adding entry methods for parsing etc. to the model objects. Those methods can then forward the work to the actual backend configured like in a strategy pattern. When you agree that this makes sense I would refactor the code accordingly.


### About the bi-directional relationships between the model objects:
You are right they have been added on purpose and work like a parent-child pattern.
Logically all the model objects define a clear hierarchy. The MHLHistory "owns" children like the MHLHashLists and the MHLChain while they should reference their parent in a weak fashion etc. I understand that there might be (at least) two problems with the current implementation.
1. The hierarchy is not so easy to see since the model names are all very similar and maybe renaming all parent style relationships to `parent` would already help to make the hierarchy more clear.
2. I honestly haven't thought at all about memory management until that point. From what you say and what I've read having weak relationships is possible but not the best thing to do in python. So in addition to that I haven't marked the parents as being weak, what is clearly a programming error, we might have a conceptional problem here.

Before thinking about a solution let me explain our intention.
I've been using this parent-child pattern a lot in non garbage collected programming languages and there it works great and makes things very easy because you can access the whole tree from every single node object.
For example consider the method `find_original_hash_entry_for_path` of the `MHLHistory`. It finds the original `MHLHashEntry` for a given file path. It basically iterates over all `MHLHashLists` and their `MHLMediaHashes` to find the according `MHLHashEntry`.
In the end it just needs to return the `MHLHashEntry` and if I as a caller of that method want to know anything about the context I can easily get it.
For example if I want to know the generation number (part of the `MHLHashList`) that this `MHLHashEntry` was found in, I just need to call `entry.mediaHash.hashList.generation_number` since all objects in the tree know about their parent.

If they would not have a parent relationship I'd need to either add a method that can find me the `MHLHashList` for a given `MHLHashEntry` what would be inefficient since it needs to iterate over all `MHLHashLists` again. And I might end up with a lot of additional utility methods.
Or the method could return all the parent objects it found on the way as well. In that case the `MHLHashList` and the `MHLMediaHash` objects could also be returned by `find_original_hash_entry_for_path` and I could access the generation number from the returned `MHLHashList`.
I'm not saying that the current implementation needs this a lot and we can probably avoid each currently existing situation if needed. But it's a nice to have and from my opinion makes the hierarchy easier to navigate and thus code simpler.
And thinking that we are basically creating a library I never know what the library users actually want to do. So I would not add the parent relationship only in some some cases we found to be useful as this would feel arbitrary for the library user.

Do you have a suggestion about this? I think returning all parents as well in such "search" methods as mentioned above would be a way to go.
But I'm not sure if that is a nice pattern and if there is a pythonic way of doing this. I could think of returning a (named?) tuple or similar, what do you think?

**Comment by jwaggs** [comment]
Thanks for the detailed response @asmpfn.

In regards to the "back end classes" discussion, I find that making design decisions based on unplanned features can usually have the opposite effect. We had proposed an additional / alternate json format about 6 months ago during the early meetings and it was denied. Had the conversation hinted at any interest in an alternate file format, I would be inclined to agree that a more robust division would make sense. I'm currently not under the impression that the division is necessary, but, if we want to keep those backends in separate files, it might be worth turning them into sub-packages that each have a 'models.py' and 'backend.py' module. I'm hesitant to convert these to sub packages though. My vote really is to still just merge them into their corresponding module because there are no pure functions in those modules currently... so the pure functions would serve as a natural separation of concerns there. If you really want to keep the _backend files though, I'd definitely say kill the static classes.

As for the bi-directional references, I think including relationships simply for the sake of it being easier to access data in any unplanned way isn't going to be beneficial here. There is a lot of clear intent and design choices to your code that are very good, but they become hidden from the reader when unnecessary relationships get sprinkled in. I see your argument I'm just not inclined to agree that the simplicity of being able to reference both directions outweighs the decreased readability. As someone who had to come in and read this code and determine the intent from scratch, the bi-directional dependencies are what made the model design harder for me to wrap my head around. Even if it makes the hierarchy easier to programmatically navigate, it also makes it harder to understand. There are a couple places where I agree it might make sense to keep them for look ups. I'd love to talk through each of these modules individually when we can both work on a similar day.  I think you've got a lot of great stuff here, we just need to finalize a module and class dependency structure. This might be worth hashing out on a call so we don't play tag for a while. Thoughts?

**Comment by asmpfn** [comment]
@jwaggs I've merged all the work we were doing on the library implementation, it contains the latest changes as dicsussed about the xml scheme and directory hashes. It also addresses a lot of your feedback from above.

For the directory hases I have now added the names of the files/folders contained in a directory into the hash without using any separator since I don't think it's needed and just makes things more complicated.

I've also removed the circular dependencies in the model objects and moved the history parsing into the history.py file directly. I've kept the xml and chain parser in a separate file for now because they contain so specific code and I wanted to avoid cluttering the existing hashlist file. But I removed the class and static methods and the methods are only called from within the history implementation.

I've also added a lot more tests and Patrick cleaned up the README and terminal output.

We feel like this is now a big step forward compared to the old implementation, even if there are still some open topics and a good starting point for others to take a look and contribute to the code.

It would be great if you could take a nother look and let me know if there is still anything you would like to have changed before merging this into the master branch.

Thanks, Alex

**Pull request merged**
