### PR TITLE
Initial Review

### PR DESCRIPTION
**Pull request by jwaggs**
This PR is an initial attempt to get the project structure under control, and to establish a few "best practices". 

- Closes: issue #2 
The project has been restructured for better organization and maintainability.

- Closes: issue #3 
The code has had all print statements removed in favor of a central logger.

- Closes: issue #4 
The sub-process invocation was causing significant overhead. This script now uses internal routines to generate all hashes. When testing these changes against a ~5000 file structure, this pull request was **~15 times faster**. That gap becomes larger as the structure grows.

```
Before Pull-Request:
real	  0m17.943s
user   0m8.237s
sys	  0m8.371s
```

```
After Pull-Request:
real	 0m1.313s
user  0m0.877s
sys	 0m0.367s
```

- Closes: issue #6 
I have created a context for the CLI that stores root runtime configurations.. many of which are directly initialized from CLI arguments upon invocation. We should convert all of the classes to refer to the context to retrieve these values when needed, rather than storing them on the media_hash_list classes themselves.

### CODE REVIEW

**Comment by ptrpfn** [comment]
I looked into the 'initial-review' branch, great refactoring work! The virtual environment also now works well for me.

I have the following comments:

* I'd like to un-ignore *.ascmhl again and adding the sample ascmhl files again. Having the resulting ascmhl file for each scenario in the repository for everyone to see without the need to run scripts was one (if not _the_) main purpose of the repository.

* I see a few errors now when running either `_test_all.sh` and/or `_create_README.sh` , such as
```
cannot create xxhash for: Clips/A002C006_141024_R2EC.mov
no media_hash for A002R2EC
no media_hash for A003R2EC
```
but also
```
Error: no such option: -u
Error: no such option: -d
```

I didn't have time to take a look yet, but in case @jwaggs you see the reason for these at first sight, it might be easier for you to fix.

* One more task would be going through the various changes in the `/Scenarios/README.md`  file (see attached diff screenshot). This file is created by the `_create_README.sh` script, the intention is to illustrate the behavior of the sample implementation in ordetr to illustrate the semantics of ascmhl. Again, having that file online in the repository for easy reference in discussions and meetings (e.g. with non-developers) was part of the efforts for the repository.

Screen Shot 2019-10-02 at 16 04 37

I'm sure not all changes are critical, and some are definitively improvements, but I also see a few missing lines. Maybe again @jwaggs can you give it a quick look what's an intended change, and what's a regression? Thank you!

**Comment by jwaggs** [comment]
Thanks for the update. I was uncertain whether those output files were intended to actually be included in the repo. Now that I understand the purpose they serve, I agree they should be committed again and removed from the gitignore. That was a faulty assumption on my part.

As for the "regressions", I definitely did not intend on introducing any... so seeing as you are experiencing this, it is quite possible I have made a mistake, or that I made a change that had an implication that I did not consider. I will let you know when I get a chance to investigate further.

**Comment by ptrpfn** [comment]
Great, thanks! When I can help to fix or improve things, let me know.

**Comment by jwaggs** [comment]
Okay, all of the issues you mentioned have been solved. 

When originally refactoring the code for this PR, I had changed a few options on the `verify` command. At the time, I had removed `username` as an option entirely and simply set it to the system username. I had also changed the `directory_hashes` flag to `files_only` and flipped the default. I've since decided this change is more appropriate in it's own issue and pull request. That functionality has been reverted, however I do still set the username to the logged in user if the username is not provided as an option at run-time. I also added underscores to the multi word options. Let me know if there is any reason we don't want to do that. 

I'll open a separate issue to start the discussion of how the commands/arguments/options should be defined and what their defaults should be. We can address that in a separate pull request entirely.

I've also removed the scenario outputs from git-ignore and committed them again. 

Let me know if you find anything else.

**Comment by jwaggs** [comment]
From our discussions on Slack earlier it sounds like you have been tweaking some behavior to get the "Scenarios" to behave more appropriately. I consider it bad practice for multiple contributors to be committing on top of each other without bi-directional code reviews inside of a single pull request. I'm saying this proactively because it hasn't happened yet. My suggestion would be either: 

1. Approve then merge this pull request without adding any more commits to it. Once this PR is merged, you can then open a new pull request into `master` with your new changes, at which time I can review them.

2. Or, if you feel your changes should be merged into `master` at the same time as the rest of this pull request, then the correct flow would be for you to open a new pull request into this `initial-review` branch so that I can review and accept your changes prior to you reviewing and accepting my changes in this pull request.

The choice between those is yours. I'm not sure what the scope of your changes is at the moment. You can choose the more appropriate option between those accordingly.

**Comment by jwaggs** [comment]
I believe I've addressed all of the issues that we discussed on our phone call. To recap, my goal was to ensure that the _create_README.sh script generated output that was compatible with the state of the master branch. The necessary changes to accomplish this were:

1. Change a few verbose level logs to info level so that they always print.
2. Added a dual info log next to a critical error log indicating how many failures occurred. This is only necessary because stderr isn't being read during the readme creation script. See the relevant todo that I included in commit 223b14c ... the info log should be removed once stderr is being read properly.
3. I changed the default generation number to 1 instead of 0. This resolved the issue of everything being detected as an original, even if it was previously verified. The issue was simply that generation 0 never exists, so the default of 0 ensured that all files were repeatedly detected as new.

Let me know if you have any other concerns. As discussed on the phone call, the project should eventually be adapted to use an actual unit testing library to make errors more clear moving forward.

**Pull request merged**
