### PR TITLE
Ignore Specification

### PR DESCRIPTION
**Pull request by jwaggs**
This is a rebased version of PR #31 which will be closed in favor of this one.

Two flags have been added in this PR to the create, verify, diff, and directory_hash commands. These flags allow for an ignore file or a list of file patterns to be supplied to the commands. The traversal logic adheres to these ignore patterns now as well, skipping over any file or folder that matches supplied patterns. 

XML integration is still missing and I still need to write some tests. This PR should not be merged until tests and xml integration have been written.

In the mean time though this should be enough to serve as a draft for the actual "ignore-spec" command specification and pattern matching. If all looks good we can start integrating it with the xml.

### CODE REVIEW

**Comment by ptr-rennstoff** [comment]
Found one issue, the command
`./ascmhl.py verify -v -i A002C006_141024_R2EC.mov /Users/ptr/Desktop/B002R2EC/` led to an error (see trace below). 

The very similar `create` command
`./ascmhl.py create -v -i A002C007_141024_R2EC.mov /Users/ptr/Desktop/B002R2EC` worked without problems.

Trace:
```
$ ./ascmhl.py verify -v -i A002C006_141024_R2EC.mov /Users/ptr/Desktop/B002R2EC/
check folder at path: /Users/ptr/Desktop/B002R2EC/
Traceback (most recent call last):
  File "./ascmhl.py", line 33, in <module>
    mhltool_cli()
  File "/Users/ptr/Development/MediaHashList/mhl/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ptr/Development/MediaHashList/mhl/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ptr/Development/MediaHashList/mhl/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ptr/Development/MediaHashList/mhl/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ptr/Development/MediaHashList/mhl/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ptr/Development/MediaHashList/mhl/mhl/commands.py", line 189, in verify
    verify_entire_folder_against_full_history_subcommand(root_path, verbose, ignore_list, ignore_spec)
  File "/Users/ptr/Development/MediaHashList/mhl/mhl/commands.py", line 222, in verify_entire_folder_against_full_history_subcommand
    ignore_spec = ignore.spec_from(ignore_spec, ignore_list)
  File "/Users/ptr/Development/MediaHashList/mhl/mhl/ignore.py", line 20, in spec_from
    with open(ignore_filepath, 'r') as fh:
TypeError: expected str, bytes or os.PathLike object, not tuple
```

File in `B002R2EC`:
[B002R2EC.zip](https://github.com/ascmitc/mhl/files/5566851/B002R2EC.zip)

**Comment by ptrpfn** [comment]
Here is a behavior with nested ASC MHL history that's probably not intended:

`./ascmhl.py create -v -i A002C006_141024_R2EC.mov /Users/ptr/Desktop/Reels`

leads to

```
Sealing folder at path: /Users/ptr/Desktop/Reels ...
ignore patterns ['.DS_Store', 'ascmhl', 'A002C006_141024_R2EC.mov']
ignoring filepath /Users/ptr/Desktop/Reels/.DS_Store
ignoring filepath /Users/ptr/Desktop/Reels/ascmhl
ignoring filepath /Users/ptr/Desktop/Reels/A002R2EC/.DS_Store
ignoring filepath /Users/ptr/Desktop/Reels/A002R2EC/ascmhl
ignoring filepath /Users/ptr/Desktop/Reels/A002R2EC/Clips/.DS_Store
ignoring filepath /Users/ptr/Desktop/Reels/A002R2EC/Clips/A002C006_141024_R2EC.mov
  verified                      A002R2EC/Clips/A002C007_141024_R2EC.mov  OK
  calculated directory hash for A002R2EC/Clips  xxh64: d9cfdf5af87ac213
  verified                      A002R2EC/Sidecar.txt  OK
  calculated directory hash for A002R2EC  xxh64: 4d1e384f2f960840
  calculated root hash  xxh64: f209fa78c43403f7
Created new generation A002R2EC/ascmhl/0004_A002R2EC_2020-11-19_160412.mhl
Created new generation ascmhl/0003_Reels_2020-11-19_160412.mhl
ERROR: 1 missing file(s):
  A002R2EC/Clips/A002C006_141024_R2EC.mov
Error: Files referenced in the mhl history are missing
```

It looks like the ignore pattern is not passed on to nested ASC MHL histories and there the ignored file is then reported as "missing".

Here is the content of the `Reels` folder (with a few nested generations already):
[Reels.zip](https://github.com/ascmitc/mhl/files/5567637/Reels.zip)

**Comment by jwaggs** [comment]
This is all valid feedback and needs correction. I'll get back with you once I've had a chance to dive in a bit deeper.

**Comment by ptrpfn** [comment]
Understood. Added tests for these scenarios for easier reproducing.

**Comment by ptrpfn** [comment]
The basic use cases are looking very good already! 

This one works fine:

```
$ tree ~/Desktop/A002R2EC/
~/Desktop/A002R2EC/
├── Clips
│   ├── A002C006_141024_R2EC.mov
│   └── A002C007_141024_R2EC.mov
└── Sidecar.txt
$ ./ascmhl.py create -i A002C007* ~/Desktop/A002R2EC/
$ ./ascmhl.py create ~/Desktop/A002R2EC/
$ ./ascmhl.py verify -v ~/Desktop/A002R2EC/
check folder at path: /Users/ptr/Desktop/A002R2EC/
set ignore patterns
set ignore patterns
set ignore patterns
set ignore patterns
set ignore patterns
set ignore patterns
set ignore patterns
ignoring filepath /Users/ptr/Desktop/A002R2EC/.DS_Store
ignoring filepath /Users/ptr/Desktop/A002R2EC/ascmhl
ignoring filepath /Users/ptr/Desktop/A002R2EC/Clips/.DS_Store
ignoring filepath /Users/ptr/Desktop/A002R2EC/Clips/A002C007_141024_R2EC.mov
verification of file Clips/A002C006_141024_R2EC.mov: OK
verification of file Sidecar.txt: OK
$
```

But I found one issue with a similar scenario in nested histories where the ignore pattern actually gets ignored by mistake: 

```
$ tree ~/Desktop/Reels
/Users/ptr/Desktop/Reels
└── A002R2EC
    ├── Clips
    │   ├── A002C006_141024_R2EC.mov
    │   └── A002C007_141024_R2EC.mov
    └── Sidecar.txt
$ ./ascmhl.py create -i A002C007* ~/Desktop/Reels/A002R2EC/
$ ./ascmhl.py create ~/Desktop/Reels/
$ ./ascmhl.py verify -v ~/Desktop/Reels/A002R2EC/
check folder at path: /Users/ptr/Desktop/Reels/A002R2EC/
set ignore patterns
set ignore patterns
set ignore patterns
set ignore patterns
set ignore patterns
set ignore patterns
set ignore patterns
ignoring filepath /Users/ptr/Desktop/Reels/A002R2EC/.DS_Store
ignoring filepath /Users/ptr/Desktop/Reels/A002R2EC/ascmhl
ignoring filepath /Users/ptr/Desktop/Reels/A002R2EC/Clips/.DS_Store
verification of file Clips/A002C006_141024_R2EC.mov: OK
verification of file Clips/A002C007_141024_R2EC.mov: OK
verification of file Sidecar.txt: OK
$ 
```

In that scenario something is different, so that the file `A002C007_141024_R2EC.mov` gets verified although it is in the ignore pattern. Everything in the XML files looks good, so that might be something because that is a nested scenario. Content of the `Reels` folder is attached.

[Reels.zip](https://github.com/ascmitc/mhl/files/5630464/Reels.zip)

**Comment by jwaggs** [comment]
It appears in this last scenario, the parent is overwriting the child ignore spec. This is obviously a bug. Will address this and the other odd nested mhl edge cases soon. Likely pending our next discussion.

**Comment by jwaggs** [comment]
The nested history bug has been resolved in the latest commit to PR #40 .

**Comment by jwaggs** [comment]
This pull request is now complete and ready to be merged.

All merge conflicts have been resolved.

Let's merge this in prior to PR #51 @ptrpfn - I'll await your approval.

**Comment by ptrpfn** [comment]
In the existing tests I found one issue in the `test_child_history_partial_verification_bb_folder` test in `test_mhl_parsing.py`.

That one fails and it looks like if in that particular case MHL files themselves are listed in the hashlist (and not ignored properly).

**Comment by jwaggs** [comment]
@ptrpfn good catch - a bit more digging leads me to believe that in some situations, but not all, the ascmhl folder is not properly ignored. This is a bug and I'll need to investigate more to find the root cause. 

I hope to be able to wrap back around to this in the upcoming few days.

**Comment by jwaggs** [comment]
@ptrpfn I've added a commit and in that commit there is now a test case named `test_default_ignore`

do you mind taking a look at that function and possibly trying to infer why that test shows that the ascmhl folder is properly ignored by default, but in your test setup it somehow is not?

**Comment by ptrpfn** [comment]
I think I fixed the bug. It was only happening in the 'create -sf' subcommand, there the ignore spec was not passed on. Committed with 649ccb

**Comment by jwaggs** [comment]
Thanks @ptrpfn - your commit looks good to me. feel free to approve and merge this PR at your leisure, or let me know if there are any other issues.

**Review by ptrpfn — APPROVED** [review]
Looks good, tests are running.

**Pull request merged**
